-- =============================================================================
-- newsmap RAG schema
--   PostgreSQL 18.6 / pgvector 0.8.6 / pg_search 0.25.11
--   적용: psql -v ON_ERROR_STOP=1 -f contracts/schema.sql  (README 참고)
--   시각: 모두 timestamptz(0), DB 시간대 Asia/Seoul (초 단위까지 저장)
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_search;

-- -----------------------------------------------------------------------------
-- 행정구역 마스터 (행정안전부 행정표준코드, 행정동 10자리)
--   코드 구조: 시도(2) + 시군구(3) + 읍면동(3) + 리(2)
--   폐지된 코드도 삭제하지 않고 valid_to 만 채운다.
-- -----------------------------------------------------------------------------
CREATE TABLE regions (
    code         varchar(10) PRIMARY KEY,
    level        smallint    NOT NULL CHECK (level IN (1, 2, 3)),  -- 1 시도, 2 시군구, 3 읍면동
    sido_name    text        NOT NULL,
    sigungu_name text,
    emd_name     text,
    full_name    text        NOT NULL,                             -- 예: 경기도 수원시 영통구 매탄1동
    parent_code  varchar(10) REFERENCES regions (code),
    valid_from   date,
    valid_to     date                                              -- NULL 이면 현재 유효
);

CREATE INDEX regions_parent_code_idx ON regions (parent_code);
CREATE INDEX regions_full_name_idx ON regions (full_name);

-- -----------------------------------------------------------------------------
-- 통신사 (자사 생산 여부 / 이미지 라이선스 판단용 정규화 테이블)
-- -----------------------------------------------------------------------------
CREATE TABLE wire_agencies (
    id      smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    text   NOT NULL UNIQUE,                 -- 정규화된 이름
    aliases text[] NOT NULL DEFAULT '{}'            -- 기사/캡션에 나타나는 표기들
);

CREATE INDEX wire_agencies_aliases_idx ON wire_agencies USING gin (aliases);

INSERT INTO wire_agencies (name, aliases) VALUES
    ('연합뉴스', '{연합,연합뉴스,Yonhap,YNA}'),
    ('뉴시스',   '{뉴시스,NEWSIS}'),
    ('뉴스1',    '{뉴스1,News1}'),
    ('AP',       '{AP,AP통신,AP연합}'),
    ('AFP',      '{AFP,AFP통신,AFP연합}'),
    ('로이터',   '{로이터,Reuters,로이터연합}'),
    ('EPA',      '{EPA,EPA연합}');

-- -----------------------------------------------------------------------------
-- 섹션 (대분류 6개 고정)
-- -----------------------------------------------------------------------------
CREATE TABLE sections (
    id   smallint PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL UNIQUE
);

INSERT INTO sections (id, code, name) VALUES
    (1, 'politics', '정치'),
    (2, 'economy',  '경제'),
    (3, 'society',  '사회'),
    (4, 'culture',  '문화'),   -- 생활, 연예 포함
    (5, 'sports',   '스포츠'),
    (6, 'science',  '과학');   -- IT 포함

-- -----------------------------------------------------------------------------
-- 기사
--   피드/언론사는 설정 파일에서 관리하므로 feed_key, publisher_name 을 그대로 저장한다.
--   제목/부제목/본문은 HTML 태그와 특수문자를 제거한 값이다.
--   기사 + 하위 테이블 + seen_rss_links 는 모든 처리가 끝난 뒤 한 트랜잭션으로 저장한다.
-- -----------------------------------------------------------------------------
CREATE TABLE articles (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_key            text NOT NULL,
    publisher_name      text NOT NULL,
    rss_link            text NOT NULL,
    canonical_url       text NOT NULL UNIQUE,
    title               text NOT NULL,
    subtitle            text,
    body                text NOT NULL,
    reporters           text[] NOT NULL DEFAULT '{}',
    -- NULL: 자사 생산 또는 판단 불가 / 값: 통신사 기사
    wire_agency_id      smallint REFERENCES wire_agencies (id),
    wire_source_raw     text,                                    -- LLM 이 찾은 원문 표기
    published_at        timestamptz(0) NOT NULL,
    published_at_source text NOT NULL
        CHECK (published_at_source IN ('rss_published', 'rss_created', 'collected')),
    rss_created_at      timestamptz(0),
    rss_updated_at      timestamptz(0),                          -- 재파싱 없이 최신값만 갱신
    created_at          timestamptz(0) NOT NULL DEFAULT now(),   -- 수집 시각
    updated_at          timestamptz(0) NOT NULL DEFAULT now()
);

CREATE INDEX articles_feed_key_rss_link_idx ON articles (feed_key, rss_link);
CREATE INDEX articles_published_at_idx ON articles (published_at);
CREATE INDEX articles_created_at_idx ON articles (created_at);       -- 보존기간(1년) 삭제용

-- -----------------------------------------------------------------------------
-- 이미 본 RSS 항목 (기사 페이지를 열기 전 중복 필터)
--   canonical_url 중복으로 버린 항목도 기존 기사 id 로 기록해 다시 열지 않는다.
-- -----------------------------------------------------------------------------
CREATE TABLE seen_rss_links (
    feed_key   text   NOT NULL,
    rss_link   text   NOT NULL,
    article_id bigint NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    created_at timestamptz(0) NOT NULL DEFAULT now(),
    PRIMARY KEY (feed_key, rss_link)
);

CREATE INDEX seen_rss_links_article_id_idx ON seen_rss_links (article_id);

-- -----------------------------------------------------------------------------
-- 기사-지역 (N:M)
--   코드: regions 에 매칭된 값 (매칭 실패 시 NULL), 이름: LLM 이 돌려준 원문
--   시군구/읍면동 판단이 어려우면 해당 단위 NULL, 지역 무관 기사는 행 없음.
-- -----------------------------------------------------------------------------
CREATE TABLE article_regions (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id   bigint NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    sido_code    varchar(10) REFERENCES regions (code),
    sigungu_code varchar(10) REFERENCES regions (code),
    emd_code     varchar(10) REFERENCES regions (code),
    sido_name    text,
    sigungu_name text,
    emd_name     text,
    is_primary   boolean NOT NULL DEFAULT false,
    UNIQUE NULLS NOT DISTINCT (article_id, sido_code, sigungu_code, emd_code, sido_name, sigungu_name, emd_name)
);

CREATE INDEX article_regions_article_id_idx ON article_regions (article_id);
CREATE INDEX article_regions_sido_code_idx ON article_regions (sido_code);
CREATE INDEX article_regions_sigungu_code_idx ON article_regions (sigungu_code);
CREATE INDEX article_regions_emd_code_idx ON article_regions (emd_code);
CREATE UNIQUE INDEX article_regions_one_primary_idx ON article_regions (article_id) WHERE is_primary;

-- -----------------------------------------------------------------------------
-- 기사-섹션 (N:M, 되도록 1개 / 대표 섹션은 is_primary)
-- -----------------------------------------------------------------------------
CREATE TABLE article_sections (
    article_id bigint   NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    section_id smallint NOT NULL REFERENCES sections (id),
    is_primary boolean  NOT NULL DEFAULT false,
    PRIMARY KEY (article_id, section_id)
);

CREATE INDEX article_sections_section_id_idx ON article_sections (section_id);
CREATE UNIQUE INDEX article_sections_one_primary_idx ON article_sections (article_id) WHERE is_primary;

-- -----------------------------------------------------------------------------
-- 기사 이미지 (썸네일 포함)
--   license_agency_id: NULL 이면 자사 또는 라이선스 표시 없음
-- -----------------------------------------------------------------------------
CREATE TABLE article_images (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id        bigint   NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    position          smallint NOT NULL,                       -- 본문 내 순서 (0부터)
    image_url         text     NOT NULL,
    caption           text,
    credit_raw        text,                                    -- 캡션에서 찾은 출처 원문 (예: 연합뉴스 제공)
    license_agency_id smallint REFERENCES wire_agencies (id),
    is_thumbnail      boolean  NOT NULL DEFAULT false,
    UNIQUE (article_id, position)
);

CREATE UNIQUE INDEX article_images_one_thumbnail_idx ON article_images (article_id) WHERE is_thumbnail;

-- -----------------------------------------------------------------------------
-- 본문 청크
--   content:    원문 청크 (오버랩 포함, Qwen3 토크나이저 기준 최대 500 토큰)
--   embed_text: 임베딩/BM25 대상. 지역·날짜·제목 헤더 + content
--   아래 필터용 컬럼은 articles / article_regions / article_sections 를 비정규화한 값으로,
--   기사 저장 트랜잭션에서 함께 채운다.
--     region_codes: 기사 지역 코드를 상위 단위까지 펼친 값 (매탄1동 → 매탄1동, 영통구, 경기도)
--     is_wire:      articles.wire_agency_id IS NOT NULL
-- -----------------------------------------------------------------------------
CREATE TABLE article_chunks (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id   bigint  NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    chunk_index  integer NOT NULL,                             -- 0부터
    content      text    NOT NULL,
    embed_text   text    NOT NULL,
    token_count  integer NOT NULL,
    embedding    halfvec(1024) NOT NULL,                       -- Qwen3-Embedding-0.6B, 1024차원
    region_codes varchar(10)[] NOT NULL DEFAULT '{}',
    section_ids  smallint[]    NOT NULL DEFAULT '{}',
    published_at timestamptz(0) NOT NULL,
    is_wire      boolean NOT NULL DEFAULT false,
    created_at   timestamptz(0) NOT NULL DEFAULT now(),
    UNIQUE (article_id, chunk_index)
);

CREATE INDEX article_chunks_embedding_idx ON article_chunks
    USING hnsw (embedding halfvec_cosine_ops) WITH (m = 16, ef_construction = 64);

CREATE INDEX article_chunks_region_codes_idx ON article_chunks USING gin (region_codes);
CREATE INDEX article_chunks_section_ids_idx ON article_chunks USING gin (section_ids);
CREATE INDEX article_chunks_published_at_idx ON article_chunks (published_at);

-- BM25 (한국어 형태소: Lindera KoDic). published_at, is_wire 는 필터 pushdown 용.
CREATE INDEX article_chunks_bm25_idx ON article_chunks
    USING paradedb (id, (embed_text::pdb.lindera(korean)), published_at, is_wire)
    WITH (key_field = 'id');

-- -----------------------------------------------------------------------------
-- 하이브리드 검색: BM25 + 벡터를 RRF 로 결합
--   p_query_text      : 사용자 질의 원문 (빈 문자열이면 BM25 결과 없음)
--   p_query_embedding : 같은 질의를 Qwen3-Embedding-0.6B 로 임베딩한 값 (query 용 instruction 적용)
--   필터 파라미터는 NULL 이면 적용하지 않는다. p_region_codes / p_section_ids 는 하나라도 겹치면 통과.
--   p_exclude_wire    : true 면 통신사 기사 청크 제외. 서비스에서 호출할 때마다 지정 가능.
-- -----------------------------------------------------------------------------
CREATE FUNCTION search_chunks(
    p_query_text      text,
    p_query_embedding halfvec(1024),
    p_region_codes    varchar(10)[]  DEFAULT NULL,
    p_section_ids     smallint[]     DEFAULT NULL,
    p_from            timestamptz    DEFAULT NULL,
    p_to              timestamptz    DEFAULT NULL,
    p_exclude_wire    boolean        DEFAULT true,
    p_limit           integer        DEFAULT 10,
    p_candidates      integer        DEFAULT 100,
    p_rrf_k           integer        DEFAULT 60,
    p_text_weight     double precision DEFAULT 1.0,
    p_vector_weight   double precision DEFAULT 1.0
)
RETURNS TABLE (
    chunk_id     bigint,
    article_id   bigint,
    chunk_index  integer,
    content      text,
    published_at timestamptz,
    score        double precision,
    text_rank    bigint,
    vector_rank  bigint
)
LANGUAGE sql
STABLE
-- 필터와 함께 HNSW 를 쓸 때 후보가 모자라지 않도록 iterative scan 을 켠다.
SET hnsw.iterative_scan = 'relaxed_order'
SET hnsw.ef_search = 200
AS $$
    WITH text_hits AS (
        SELECT c.id,
               row_number() OVER (ORDER BY pdb.score(c.id) DESC, c.id) AS rank
        FROM article_chunks c
        WHERE coalesce(btrim(p_query_text), '') <> ''
          AND c.embed_text ||| p_query_text
          AND (p_region_codes IS NULL OR c.region_codes && p_region_codes)
          AND (p_section_ids  IS NULL OR c.section_ids  && p_section_ids)
          AND (p_from IS NULL OR c.published_at >= p_from)
          AND (p_to   IS NULL OR c.published_at <  p_to)
          AND (NOT p_exclude_wire OR NOT c.is_wire)
        ORDER BY pdb.score(c.id) DESC, c.id
        LIMIT p_candidates
    ),
    vector_candidates AS MATERIALIZED (
        SELECT c.id,
               c.embedding <=> p_query_embedding AS distance
        FROM article_chunks c
        WHERE (p_region_codes IS NULL OR c.region_codes && p_region_codes)
          AND (p_section_ids  IS NULL OR c.section_ids  && p_section_ids)
          AND (p_from IS NULL OR c.published_at >= p_from)
          AND (p_to   IS NULL OR c.published_at <  p_to)
          AND (NOT p_exclude_wire OR NOT c.is_wire)
        ORDER BY c.embedding <=> p_query_embedding
        LIMIT p_candidates
    ),
    vector_hits AS (
        -- relaxed_order 는 순서가 살짝 어긋날 수 있어 다시 정렬한다.
        SELECT id, row_number() OVER (ORDER BY distance, id) AS rank
        FROM vector_candidates
    ),
    fused AS (
        SELECT coalesce(t.id, v.id) AS id,
               coalesce(p_text_weight   / (p_rrf_k + t.rank), 0)
             + coalesce(p_vector_weight / (p_rrf_k + v.rank), 0) AS score,
               t.rank AS text_rank,
               v.rank AS vector_rank
        FROM text_hits t
        FULL OUTER JOIN vector_hits v ON v.id = t.id
    )
    SELECT c.id, c.article_id, c.chunk_index, c.content, c.published_at,
           f.score, f.text_rank, f.vector_rank
    FROM fused f
    JOIN article_chunks c ON c.id = f.id
    ORDER BY f.score DESC, c.id
    LIMIT p_limit;
$$;

COMMIT;
